name-template: 'ğŸš€ v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'âœ¨ Features'
    labels:
      - 'feature'
      - 'feature âœ¨'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'fix ğŸ›'
  - title: 'ğŸ§° Maintenance'
    label:
      - 'chore'
      - 'docs'
      - 'chore ğŸ”¨'
      - 'docs ğŸ“'
  - title: 'âš¡ performance'
    label:
      - 'refactor'
      - 'test'
      - 'refactor â™»ï¸'
      - 'test âœ…'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## ğŸ“Œ ë³€ê²½ ì‚¬í•­
  ---
  $CHANGES
no-changes-template: 'âš ï¸ ë³€ê²½ ì‚¬í•­ì´ ì—†ì–´ìš”!'
